export const cityData = [
  {
    city: "Tehran",
    city_fa: "تهران",
    lat: "35.7000",
    lng: "51.4167",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "primary",
    population: "13633000",
    population_proper: "9033003",
  },
  {
    city: "Mashhad",
    city_fa: "مشهد",
    lat: "36.3069",
    lng: "59.6042",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "admin",
    population: "3001184",
    population_proper: "3001184",
  },
  {
    city: "Isfahan",
    city_fa: "اصفهان",
    lat: "32.6447",
    lng: "51.6675",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "admin",
    population: "1756126",
    population_proper: "1756126",
  },
  {
    city: "Karaj",
    city_fa: "کرج",
    lat: "35.8327",
    lng: "50.9915",
    country: "Iran",
    iso2: "IR",
    admin_name: "Alborz",
    capital: "admin",
    population: "1592492",
    population_proper: "1592492",
  },
  {
    city: "Tabriz",
    city_fa: "تبریز",
    lat: "38.0833",
    lng: "46.2833",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "admin",
    population: "1558693",
    population_proper: "1558693",
  },
  {
    city: "Shiraz",
    city_fa: "شیراز",
    lat: "29.6100",
    lng: "52.5425",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "admin",
    population: "1460665",
    population_proper: "1460665",
  },
  {
    city: "Qom",
    city_fa: "قم",
    lat: "34.6461",
    lng: "50.8789",
    country: "Iran",
    iso2: "IR",
    admin_name: "Qom",
    capital: "admin",
    population: "1201158",
    population_proper: "1201158",
  },
  {
    city: "Ahvaz",
    city_fa: "اهواز",
    lat: "31.3203",
    lng: "48.6692",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "admin",
    population: "1184788",
    population_proper: "1184788",
  },
  {
    city: "Kermanshah",
    city_fa: "کرمانشاه",
    lat: "34.3167",
    lng: "47.0686",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "admin",
    population: "851405",
    population_proper: "851405",
  },
  {
    city: "Urmia",
    city_fa: "ارومیه",
    lat: "37.5486",
    lng: "45.0675",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "admin",
    population: "736224",
    population_proper: "736224",
  },
  {
    city: "Rasht",
    city_fa: "رشت",
    lat: "37.2833",
    lng: "49.6000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "admin",
    population: "639951",
    population_proper: "639951",
  },
  {
    city: "Kerman",
    city_fa: "کرمان",
    lat: "30.2833",
    lng: "57.0667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "admin",
    population: "573449",
    population_proper: "573449",
  },
  {
    city: "Zahedan",
    city_fa: "زاهدان",
    lat: "29.4833",
    lng: "60.8667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "admin",
    population: "560725",
    population_proper: "560725",
  },
  {
    city: "Islamshahr",
    city_fa: "اسلامشهر",
    lat: "35.5333",
    lng: "51.2000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "548620",
    population_proper: "548620",
  },
  {
    city: "Hamadan",
    city_fa: "همدان",
    lat: "34.8065",
    lng: "48.5162",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hamadān",
    capital: "admin",
    population: "528256",
    population_proper: "330",
  },
  {
    city: "Yazd",
    city_fa: "یزد",
    lat: "31.8972",
    lng: "54.3678",
    country: "Iran",
    iso2: "IR",
    admin_name: "Yazd",
    capital: "admin",
    population: "486152",
    population_proper: "486152",
  },
  {
    city: "Arak",
    city_fa: "اراک",
    lat: "34.0800",
    lng: "49.7000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "admin",
    population: "484212",
    population_proper: "484212",
  },
  {
    city: "Ardabil",
    city_fa: "اردبیل",
    lat: "38.2500",
    lng: "48.3000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Ardabīl",
    capital: "admin",
    population: "482632",
    population_proper: "482632",
  },
  {
    city: "Bandar Abbas",
    city_fa: "بندرعباس",
    lat: "27.2000",
    lng: "56.2500",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "admin",
    population: "435751",
    population_proper: "435751",
  },
  {
    city: "Zanjan",
    city_fa: "زنجان",
    lat: "36.6667",
    lng: "48.4833",
    country: "Iran",
    iso2: "IR",
    admin_name: "Zanjān",
    capital: "admin",
    population: "433475",
    population_proper: "433475",
  },
  {
    city: "Kashan",
    city_fa: "کاشان",
    lat: "33.9833",
    lng: "51.4333",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "432557",
    population_proper: "432557",
  },
  {
    city: "Qazvin",
    city_fa: "قزوین",
    lat: "36.2688",
    lng: "50.0041",
    country: "Iran",
    iso2: "IR",
    admin_name: "Qazvīn",
    capital: "admin",
    population: "381598",
    population_proper: "381598",
  },
  {
    city: "Sanandaj",
    city_fa: "سنندج",
    lat: "35.3097",
    lng: "46.9989",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kordestān",
    capital: "admin",
    population: "373987",
    population_proper: "373987",
  },
  {
    city: "Madan",
    city_fa: "معدن",
    lat: "30.3307",
    lng: "48.2797",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "",
    population: "370180",
    population_proper: "260078",
  },
  {
    city: "Khorramabad",
    city_fa: "خرم آباد",
    lat: "33.4667",
    lng: "48.3500",
    country: "Iran",
    iso2: "IR",
    admin_name: "Lorestān",
    capital: "admin",
    population: "348216",
    population_proper: "348216",
  },
  {
    city: "Gorgan",
    city_fa: "گرگان",
    lat: "36.8300",
    lng: "54.4800",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "admin",
    population: "312223",
    population_proper: "312223",
  },
  {
    city: "Shahriar",
    city_fa: "شهریار",
    lat: "35.6597",
    lng: "51.0592",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "309607",
    population_proper: "309607",
  },
  {
    city: "Shahr-e Qods",
    city_fa: "شهر قدس",
    lat: "35.7214",
    lng: "51.1089",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "309605",
    population_proper: "309605",
  },
  {
    city: "Malard",
    city_fa: "ملارد",
    lat: "35.6658",
    lng: "50.9767",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "281027",
    population_proper: "281027",
  },
  {
    city: "Sari",
    city_fa: "ساری",
    lat: "36.5504",
    lng: "53.1000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "",
    population: "271467",
    population_proper: "255396",
  },
  {
    city: "Dezful",
    city_fa: "دزفول",
    lat: "32.3878",
    lng: "48.4033",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "264709",
    population_proper: "264709",
  },
  {
    city: "Babolsar",
    city_fa: "بابلسر",
    lat: "36.5500",
    lng: "52.6833",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "250217",
    population_proper: "250217",
  },
  {
    city: "Bukan",
    city_fa: "بوکان",
    lat: "36.5208",
    lng: "46.2117",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "248900",
    population_proper: "248900",
  },
  {
    city: "Sabzevar",
    city_fa: "سبزوار",
    lat: "36.2167",
    lng: "57.6667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "243700",
    population_proper: "243700",
  },
  {
    city: "Amol",
    city_fa: "آمل",
    lat: "36.4669",
    lng: "52.3569",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "237528",
    population_proper: "237528",
  },
  {
    city: "Pakdasht",
    city_fa: "پاکدشت",
    lat: "35.4817",
    lng: "51.6803",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "236319",
    population_proper: "236319",
  },
  {
    city: "Najafabad",
    city_fa: "نجف آباد",
    lat: "32.6342",
    lng: "51.3667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "235281",
    population_proper: "235281",
  },
  {
    city: "Borujerd",
    city_fa: "بروجرد",
    lat: "33.8972",
    lng: "48.7514",
    country: "Iran",
    iso2: "IR",
    admin_name: "Lorestān",
    capital: "minor",
    population: "234997",
    population_proper: "234997",
  },
  {
    city: "Qarchak",
    city_fa: "قرچک",
    lat: "35.4394",
    lng: "51.5689",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "",
    population: "231075",
    population_proper: "231075",
  },
  {
    city: "Varamin",
    city_fa: "ورامین",
    lat: "35.2714",
    lng: "51.6511",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "225628",
    population_proper: "225628",
  },
  {
    city: "Neyshabur",
    city_fa: "نیشابور",
    lat: "36.2200",
    lng: "58.8200",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "221700",
    population_proper: "220929",
  },
  {
    city: "Sāveh",
    city_fa: "ساوه",
    lat: "35.0211",
    lng: "50.3564",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "minor",
    population: "220762",
    population_proper: "220762",
  },
  {
    city: "Khomeynī Shahr",
    city_fa: "خمینی‌شهر",
    lat: "32.7000",
    lng: "51.5211",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "218737",
    population_proper: "218737",
  },
  {
    city: "Qā’em Shahr",
    city_fa: "قائم‌شهر",
    lat: "36.4611",
    lng: "52.8606",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "",
    population: "204953",
    population_proper: "204953",
  },
  {
    city: "Nasīm Shahr",
    city_fa: "نسیم‌شهر",
    lat: "35.5644",
    lng: "51.1647",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "200393",
    population_proper: "200393",
  },
  {
    city: "Bojnūrd",
    city_fa: "بجنورد",
    lat: "37.4667",
    lng: "57.3333",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Shomālī",
    capital: "admin",
    population: "199791",
    population_proper: "199791",
  },
  {
    city: "Bandar-e Būshehr",
    city_fa: "بندر بوشهر",
    lat: "28.9667",
    lng: "50.8333",
    country: "Iran",
    iso2: "IR",
    admin_name: "Būshehr",
    capital: "admin",
    population: "195222",
    population_proper: "195222",
  },
  {
    city: "Semnān",
    city_fa: "سمنان",
    lat: "35.5833",
    lng: "53.3833",
    country: "Iran",
    iso2: "IR",
    admin_name: "Semnān",
    capital: "admin",
    population: "185129",
    population_proper: "185129",
  },
  {
    city: "Khowy",
    city_fa: "خوی",
    lat: "38.5503",
    lng: "44.9519",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "182000",
    population_proper: "182000",
  },
  {
    city: "Fardīs",
    city_fa: "فردیس",
    lat: "35.7247",
    lng: "50.9883",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "",
    population: "181174",
    population_proper: "181174",
  },
  {
    city: "Bīrjand",
    city_fa: "بیرجند",
    lat: "32.8664",
    lng: "59.2211",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Jonūbī",
    capital: "admin",
    population: "178020",
    population_proper: "178020",
  },
  {
    city: "Marāgheh",
    city_fa: "مراغه",
    lat: "37.3919",
    lng: "46.2392",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "175255",
    population_proper: "175255",
  },
  {
    city: "Sīrjān",
    city_fa: "سیرجان",
    lat: "29.4700",
    lng: "55.7300",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "175000",
    population_proper: "167014",
  },
  {
    city: "Shāhīn Shahr",
    city_fa: "شاهین‌شهر",
    lat: "32.8639",
    lng: "51.5475",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "173329",
    population_proper: "173329",
  },
  {
    city: "Malāyer",
    city_fa: "ملایر",
    lat: "34.2942",
    lng: "48.8200",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hamadān",
    capital: "minor",
    population: "170237",
    population_proper: "170237",
  },
  {
    city: "Mahābād",
    city_fa: "مهاباد",
    lat: "36.7650",
    lng: "45.7210",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "",
    population: "168393",
    population_proper: "168393",
  },
  {
    city: "Saqqez",
    city_fa: "سقز",
    lat: "36.2497",
    lng: "46.2733",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kordestān",
    capital: "minor",
    population: "165258",
    population_proper: "165258",
  },
  {
    city: "Bandar-e Māhshahr",
    city_fa: "بندر ماهشهر",
    lat: "30.5589",
    lng: "49.1981",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "162797",
    population_proper: "162797",
  },
  {
    city: "Rafsanjān",
    city_fa: "رفسنجان",
    lat: "30.4000",
    lng: "56.0000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "161909",
    population_proper: "161909",
  },
  {
    city: "Shahr-e Kord",
    city_fa: "شهرکرد",
    lat: "32.3256",
    lng: "50.8644",
    country: "Iran",
    iso2: "IR",
    admin_name: "Chahār Maḩāl va Bakhtīārī",
    capital: "admin",
    population: "159775",
    population_proper: "159775",
  },
  {
    city: "Golmeh",
    city_fa: "گل‌مهر",
    lat: "33.7793",
    lng: "46.5967",
    country: "Iran",
    iso2: "IR",
    admin_name: "Īlām",
    capital: "",
    population: "152894",
    population_proper: "140940",
  },
  {
    city: "Gonbad-e Kāvūs",
    city_fa: "گنبد کاووس",
    lat: "37.2500",
    lng: "55.1672",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "151910",
    population_proper: "151910",
  },
  {
    city: "Shāhrūd",
    city_fa: "شاهرود",
    lat: "36.4086",
    lng: "54.9733",
    country: "Iran",
    iso2: "IR",
    admin_name: "Semnān",
    capital: "minor",
    population: "150129",
    population_proper: "150129",
  },
  {
    city: "Marvdasht",
    city_fa: "مرودشت",
    lat: "29.8742",
    lng: "52.8025",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "148858",
    population_proper: "148858",
  },
  {
    city: "Qūchān",
    city_fa: "قوچان",
    lat: "37.1118",
    lng: "58.5015",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "145531",
    population_proper: "111752",
  },
  {
    city: "Jahrom",
    city_fa: "جهرم",
    lat: "28.5000",
    lng: "53.5600",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "141634",
    population_proper: "141634",
  },
  {
    city: "Kamālshahr",
    city_fa: "کمالشهر",
    lat: "35.8622",
    lng: "50.8717",
    country: "Iran",
    iso2: "IR",
    admin_name: "Alborz",
    capital: "",
    population: "141166",
    population_proper: "141166",
  },
  {
    city: "Torbat-e Ḩeydarīyeh",
    city_fa: "تربت حیدریه",
    lat: "35.2739",
    lng: "59.2194",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "140019",
    population_proper: "140019",
  },
  {
    city: "Pīrānshahr",
    city_fa: "پیرانشهر",
    lat: "36.6944",
    lng: "45.1417",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "138864",
    population_proper: "138864",
  },
  {
    city: "Marīvān",
    city_fa: "مریوان",
    lat: "35.5269",
    lng: "46.1761",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kordestān",
    capital: "minor",
    population: "136654",
    population_proper: "136654",
  },
  {
    city: "Andīmeshk",
    city_fa: "اندیمشک",
    lat: "32.4500",
    lng: "48.3500",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "135116",
    population_proper: "135116",
  },
  {
    city: "Shahreẕā",
    city_fa: "شهرضا",
    lat: "32.0089",
    lng: "51.8667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "134592",
    population_proper: "134592",
  },
  {
    city: "Zābol",
    city_fa: "زابل",
    lat: "31.0308",
    lng: "61.4972",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "134590",
    population_proper: "134590",
  },
  {
    city: "Khorramshahr",
    city_fa: "خرمشهر",
    lat: "30.4333",
    lng: "48.1833",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "133097",
    population_proper: "133097",
  },
  {
    city: "Marand",
    city_fa: "مرند",
    lat: "38.4167",
    lng: "45.7667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "130825",
    population_proper: "130825",
  },
  {
    city: "Jīroft",
    city_fa: "جیرفت",
    lat: "28.6781",
    lng: "57.7406",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "130429",
    population_proper: "130429",
  },
  {
    city: "Salmās",
    city_fa: "سلماس",
    lat: "38.2000",
    lng: "44.7667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "127864",
    population_proper: "127864",
  },
  {
    city: "Bam",
    city_fa: "بام",
    lat: "29.1083",
    lng: "58.3583",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "127396",
    population_proper: "127396",
  },
  {
    city: "Behbahān",
    city_fa: "بهبهان",
    lat: "30.5958",
    lng: "50.2417",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "122604",
    population_proper: "122604",
  },
  {
    city: "Dorūd",
    city_fa: "دورود",
    lat: "33.4933",
    lng: "49.0750",
    country: "Iran",
    iso2: "IR",
    admin_name: "Lorestān",
    capital: "minor",
    population: "121608",
    population_proper: "121608",
  },
  {
    city: "Naz̧arābād",
    city_fa: "نظرآباد",
    lat: "35.9522",
    lng: "50.6075",
    country: "Iran",
    iso2: "IR",
    admin_name: "Alborz",
    capital: "minor",
    population: "119512",
    population_proper: "119512",
  },
  {
    city: "Moḩammad Shahr",
    city_fa: "محمدشهر",
    lat: "35.7631",
    lng: "50.9172",
    country: "Iran",
    iso2: "IR",
    admin_name: "Alborz",
    capital: "",
    population: "119418",
    population_proper: "119418",
  },
  {
    city: "Fasā",
    city_fa: "فسا",
    lat: "28.9381",
    lng: "53.6481",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "110825",
    population_proper: "110825",
  },
  {
    city: "Bandar-e Anzalī",
    city_fa: "بندر انزلی",
    lat: "37.4667",
    lng: "49.4667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "110643",
    population_proper: "110643",
  },
  {
    city: "Borāzjān",
    city_fa: "برازجان",
    lat: "29.2667",
    lng: "51.2158",
    country: "Iran",
    iso2: "IR",
    admin_name: "Būshehr",
    capital: "minor",
    population: "110567",
    population_proper: "110567",
  },
  {
    city: "Bāneh",
    city_fa: "بانە",
    lat: "35.9975",
    lng: "45.8853",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kordestān",
    capital: "minor",
    population: "110218",
    population_proper: "110218",
  },
  {
    city: "Yāsūj",
    city_fa: "یاسوج",
    lat: "30.6667",
    lng: "51.5833",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kohgīlūyeh va Bowyer Aḩmad",
    capital: "admin",
    population: "108505",
    population_proper: "108505",
  },
  {
    city: "Chābahār",
    city_fa: "چابهار",
    lat: "25.2836",
    lng: "60.6236",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "106739",
    population_proper: "106739",
  },
  {
    city: "Robāţ Karīm",
    city_fa: "رباط کریم",
    lat: "35.4847",
    lng: "51.0828",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "105393",
    population_proper: "105393",
  },
  {
    city: "Khāk-e ‘Alī",
    city_fa: "خاکعلی",
    lat: "36.1283",
    lng: "50.1764",
    country: "Iran",
    iso2: "IR",
    admin_name: "Qazvīn",
    capital: "",
    population: "104417",
    population_proper: "104417",
  },
  {
    city: "Kāshmar",
    city_fa: "کاشمر",
    lat: "35.2383",
    lng: "58.4656",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "102282",
    population_proper: "102282",
  },
  {
    city: "Shūshtar",
    city_fa: "شوشتر",
    lat: "32.0436",
    lng: "48.8569",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "101878",
    population_proper: "101878",
  },
  {
    city: "Ahar",
    city_fa: "اهر",
    lat: "38.4750",
    lng: "47.0603",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "100641",
    population_proper: "100641",
  },
  {
    city: "Masjed Soleymān",
    city_fa: "مسجد سلیمان",
    lat: "31.9333",
    lng: "49.3000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "100497",
    population_proper: "100497",
  },
  {
    city: "Torbat-e Jām",
    city_fa: "تربت جام",
    lat: "35.2439",
    lng: "60.6225",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "100449",
    population_proper: "100449",
  },
  {
    city: "Kāzerūn",
    city_fa: "کازرون",
    lat: "29.6167",
    lng: "51.6500",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "96683",
    population_proper: "96683",
  },
  {
    city: "Khowrāsgān",
    city_fa: "خورآسگان",
    lat: "32.6536",
    lng: "51.7550",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "",
    population: "86063",
    population_proper: "86063",
  },
  {
    city: "Shīrvān",
    city_fa: "شیروان",
    lat: "37.3967",
    lng: "57.9294",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Shomālī",
    capital: "minor",
    population: "82790",
    population_proper: "82790",
  },
  {
    city: "Meybod",
    city_fa: "میبد",
    lat: "32.2500",
    lng: "54.0167",
    country: "Iran",
    iso2: "IR",
    admin_name: "Yazd",
    capital: "minor",
    population: "80712",
    population_proper: "80712",
  },
  {
    city: "Būmahen",
    city_fa: "بومهن",
    lat: "35.7297",
    lng: "51.8619",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "",
    population: "79034",
    population_proper: "79034",
  },
  {
    city: "Alīgūdarz",
    city_fa: "الیگودرز",
    lat: "33.4006",
    lng: "49.6947",
    country: "Iran",
    iso2: "IR",
    admin_name: "Lorestān",
    capital: "minor",
    population: "78690",
    population_proper: "78690",
  },
  {
    city: "Bonāb",
    city_fa: "بناب",
    lat: "37.3403",
    lng: "46.0561",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "75332",
    population_proper: "75332",
  },
  {
    city: "Tākestān",
    city_fa: "تاکستان",
    lat: "36.0694",
    lng: "49.6958",
    country: "Iran",
    iso2: "IR",
    admin_name: "Qazvīn",
    capital: "minor",
    population: "73625",
    population_proper: "73625",
  },
  {
    city: "Oshnavīyeh",
    city_fa: "اشنویه",
    lat: "37.0397",
    lng: "45.0983",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "70030",
    population_proper: "70030",
  },
  {
    city: "Bandar-e Genāveh",
    city_fa: "بندر گناوه",
    lat: "29.5833",
    lng: "50.5167",
    country: "Iran",
    iso2: "IR",
    admin_name: "Būshehr",
    capital: "minor",
    population: "64110",
    population_proper: "64110",
  },
  {
    city: "Zarand",
    city_fa: "زرند",
    lat: "30.8128",
    lng: "56.5639",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "63744",
    population_proper: "63744",
  },
  {
    city: "Māhdāsht",
    city_fa: "مهدشهر",
    lat: "35.7283",
    lng: "50.8133",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "",
    population: "62910",
    population_proper: "62910",
  },
  {
    city: "Mobārakeh",
    city_fa: "مبارکه",
    lat: "32.3464",
    lng: "51.5044",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "62454",
    population_proper: "62454",
  },
  {
    city: "Esfarāyen",
    city_fa: "اسفراین",
    lat: "37.0764",
    lng: "57.5100",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Shomālī",
    capital: "minor",
    population: "59490",
    population_proper: "59490",
  },
  {
    city: "Dāmghān",
    city_fa: "دامغان",
    lat: "36.1681",
    lng: "54.3481",
    country: "Iran",
    iso2: "IR",
    admin_name: "Semnān",
    capital: "minor",
    population: "57331",
    population_proper: "57331",
  },
  {
    city: "Tāybād",
    city_fa: "تایباد",
    lat: "34.7400",
    lng: "60.7756",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "56562",
    population_proper: "56562",
  },
  {
    city: "Zarrīn Shahr",
    city_fa: "زرین شهر",
    lat: "32.3894",
    lng: "51.3764",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "55984",
    population_proper: "55984",
  },
  {
    city: "Ārān Bīdgol",
    city_fa: "آران و بیدگل",
    lat: "34.0578",
    lng: "51.4842",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "55651",
    population_proper: "55651",
  },
  {
    city: "Hashtpar",
    city_fa: "هشتپر",
    lat: "37.7992",
    lng: "48.9053",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "54178",
    population_proper: "54178",
  },
  {
    city: "Bījār",
    city_fa: "بیجار",
    lat: "35.8741",
    lng: "47.5937",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kordestān",
    capital: "minor",
    population: "53871",
    population_proper: "43741",
  },
  {
    city: "Sardasht",
    city_fa: "سردشت",
    lat: "36.1553",
    lng: "45.4789",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "50000",
    population_proper: "50000",
  },
  {
    city: "Rāmhormoz",
    city_fa: "رامهرمز",
    lat: "31.2783",
    lng: "49.6064",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "49822",
    population_proper: "49822",
  },
  {
    city: "Garmsār",
    city_fa: "گرمسار",
    lat: "35.2167",
    lng: "52.3333",
    country: "Iran",
    iso2: "IR",
    admin_name: "Semnān",
    capital: "minor",
    population: "48672",
    population_proper: "48672",
  },
  {
    city: "Damāvand",
    city_fa: "دماوند",
    lat: "35.7178",
    lng: "52.0650",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "48380",
    population_proper: "48380",
  },
  {
    city: "Golpāyegān",
    city_fa: "گلپایگان",
    lat: "33.4536",
    lng: "50.2883",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "47849",
    population_proper: "47849",
  },
  {
    city: "Aznā",
    city_fa: "ازنا",
    lat: "33.4539",
    lng: "49.4550",
    country: "Iran",
    iso2: "IR",
    admin_name: "Lorestān",
    capital: "minor",
    population: "47489",
    population_proper: "47489",
  },
  {
    city: "Naţanz",
    city_fa: "نطنز",
    lat: "33.5000",
    lng: "51.9000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "44000",
    population_proper: "44000",
  },
  {
    city: "Takāb",
    city_fa: "تکاب",
    lat: "36.4008",
    lng: "47.1131",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "43702",
    population_proper: "43702",
  },
  {
    city: "Darcheh",
    city_fa: "درچه",
    lat: "32.6153",
    lng: "51.5556",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "",
    population: "43183",
    population_proper: "43183",
  },
  {
    city: "Sarab",
    city_fa: "سراب",
    lat: "37.9408",
    lng: "47.5367",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "42057",
    population_proper: "42057",
  },
  {
    city: "Bāft",
    city_fa: "بافت",
    lat: "29.2331",
    lng: "56.6022",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "41105",
    population_proper: "41105",
  },
  {
    city: "Khalkhāl",
    city_fa: "خلخال",
    lat: "37.6189",
    lng: "48.5258",
    country: "Iran",
    iso2: "IR",
    admin_name: "Ardabīl",
    capital: "minor",
    population: "38521",
    population_proper: "38521",
  },
  {
    city: "Falāvarjān",
    city_fa: "فلاورجان",
    lat: "32.5553",
    lng: "51.5097",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "37740",
    population_proper: "37740",
  },
  {
    city: "Kahrīzak",
    city_fa: "کهریزک",
    lat: "35.5175",
    lng: "51.3597",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "",
    population: "37527",
    population_proper: "37527",
  },
  {
    city: "Sarpol-e Z̄ahāb",
    city_fa: "سرپل ذهاب",
    lat: "34.4614",
    lng: "45.8647",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "34632",
    population_proper: "34632",
  },
  {
    city: "Gerāsh",
    city_fa: "گراش",
    lat: "27.6650",
    lng: "54.1369",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "34469",
    population_proper: "34469",
  },
  {
    city: "Shāhīn Dezh",
    city_fa: "شاهین دژ",
    lat: "36.6792",
    lng: "46.5667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "34204",
    population_proper: "34204",
  },
  {
    city: "Khvāf",
    city_fa: "خواف",
    lat: "34.5764",
    lng: "60.1408",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "33189",
    population_proper: "33189",
  },
  {
    city: "Qahderījān",
    city_fa: "قهدریجان",
    lat: "32.5767",
    lng: "51.4550",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "",
    population: "30002",
    population_proper: "30002",
  },
  {
    city: "Evaz",
    city_fa: "اوواز",
    lat: "27.7600",
    lng: "54.0072",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "",
    population: "29987",
    population_proper: "29987",
  },
  {
    city: "Bardaskan",
    city_fa: "بردسکن",
    lat: "35.2631",
    lng: "57.9722",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "28233",
    population_proper: "28233",
  },
  {
    city: "Hādīshahr",
    city_fa: "هادی‌شهر",
    lat: "38.8478",
    lng: "45.6622",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "",
    population: "27842",
    population_proper: "27842",
  },
  {
    city: "Fūman",
    city_fa: "فومن",
    lat: "37.2239",
    lng: "49.3125",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "27763",
    population_proper: "27763",
  },
  {
    city: "Semīrom",
    city_fa: "سمیرو",
    lat: "31.4142",
    lng: "51.5694",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "26260",
    population_proper: "26260",
  },
  {
    city: "Mahdīshahr",
    city_fa: "مهدی‌شهر",
    lat: "35.7000",
    lng: "53.3500",
    country: "Iran",
    iso2: "IR",
    admin_name: "Semnān",
    capital: "minor",
    population: "24485",
    population_proper: "24485",
  },
  {
    city: "Sheybān",
    city_fa: "شیبان",
    lat: "31.4086",
    lng: "48.7942",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "",
    population: "23211",
    population_proper: "23211",
  },
  {
    city: "Kelīshād va Sūdarjān",
    city_fa: "کلیشاد و سودرجان",
    lat: "32.5542",
    lng: "51.5250",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "",
    population: "23203",
    population_proper: "23203",
  },
  {
    city: "Goldasht",
    city_fa: "گلداشت",
    lat: "32.6267",
    lng: "51.4392",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "",
    population: "22693",
    population_proper: "22693",
  },
  {
    city: "Khvānsār",
    city_fa: "خوانسار",
    lat: "33.2206",
    lng: "50.3150",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "20490",
    population_proper: "20490",
  },
  {
    city: "Kabūdarāhang",
    city_fa: "کبودرآهنگ",
    lat: "35.2083",
    lng: "48.7239",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hamadān",
    capital: "minor",
    population: "19216",
    population_proper: "19216",
  },
  {
    city: "Ashkezar",
    city_fa: "اشکذر",
    lat: "32.0000",
    lng: "54.2044",
    country: "Iran",
    iso2: "IR",
    admin_name: "Yazd",
    capital: "minor",
    population: "19123",
    population_proper: "19123",
  },
  {
    city: "Kherāmeh",
    city_fa: "خرامه",
    lat: "29.5000",
    lng: "53.3164",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "18477",
    population_proper: "18477",
  },
  {
    city: "Taft",
    city_fa: "تفت",
    lat: "31.7475",
    lng: "54.2042",
    country: "Iran",
    iso2: "IR",
    admin_name: "Yazd",
    capital: "minor",
    population: "18464",
    population_proper: "18464",
  },
  {
    city: "Feyẕābād",
    city_fa: "فیض‌آباد",
    lat: "35.0144",
    lng: "58.7800",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "18120",
    population_proper: "18120",
  },
  {
    city: "Dehāqān",
    city_fa: "دهقان",
    lat: "31.9400",
    lng: "51.6478",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "16899",
    population_proper: "16899",
  },
  {
    city: "Tīrān",
    city_fa: "تیرا",
    lat: "32.7025",
    lng: "51.1536",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "15673",
    population_proper: "15673",
  },
  {
    city: "Amlash",
    city_fa: "املش",
    lat: "37.0975",
    lng: "50.1864",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "15047",
    population_proper: "15047",
  },
  {
    city: "Ardestān",
    city_fa: "اردستان",
    lat: "33.3797",
    lng: "52.3725",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "14698",
    population_proper: "14698",
  },
  {
    city: "Fāmenīn",
    city_fa: "فامنین",
    lat: "35.1139",
    lng: "48.9717",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hamadān",
    capital: "minor",
    population: "14019",
    population_proper: "14019",
  },
  {
    city: "Fereydūnshahr",
    city_fa: "فریدون‌شهر",
    lat: "32.9411",
    lng: "50.1211",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "13475",
    population_proper: "13475",
  },
  {
    city: "Reẕvānshahr",
    city_fa: "رضوانشهر",
    lat: "37.5511",
    lng: "49.1394",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "12355",
    population_proper: "12355",
  },
  {
    city: "Ahram",
    city_fa: "اهرم",
    lat: "28.8825",
    lng: "51.2744",
    country: "Iran",
    iso2: "IR",
    admin_name: "Būshehr",
    capital: "minor",
    population: "12182",
    population_proper: "12182",
  },
  {
    city: "Poldasht",
    city_fa: "پلدشت",
    lat: "39.3481",
    lng: "45.0711",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "11472",
    population_proper: "11472",
  },
  {
    city: "Qaşr-e Shīrīn",
    city_fa: "قصر شیرین",
    lat: "34.5156",
    lng: "45.5792",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "11202",
    population_proper: "11202",
  },
  {
    city: "Sorkheh",
    city_fa: "سرخه",
    lat: "35.4633",
    lng: "53.2139",
    country: "Iran",
    iso2: "IR",
    admin_name: "Semnān",
    capital: "minor",
    population: "9951",
    population_proper: "9951",
  },
  {
    city: "Kaleybar",
    city_fa: "کلیبر",
    lat: "38.8667",
    lng: "47.0333",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "9324",
    population_proper: "9324",
  },
  {
    city: "Khondāb",
    city_fa: "خنداب",
    lat: "34.3928",
    lng: "49.1839",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "minor",
    population: "7810",
    population_proper: "7810",
  },
  {
    city: "Komījān",
    city_fa: "کمیجان",
    lat: "34.7192",
    lng: "49.3267",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "minor",
    population: "7358",
    population_proper: "7358",
  },
  {
    city: "Chādegān",
    city_fa: "چادگان",
    lat: "32.7683",
    lng: "50.6286",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "7037",
    population_proper: "7037",
  },
  {
    city: "Ārādān",
    city_fa: "آرادان",
    lat: "35.2497",
    lng: "52.4933",
    country: "Iran",
    iso2: "IR",
    admin_name: "Semnān",
    capital: "minor",
    population: "6257",
    population_proper: "6257",
  },
  {
    city: "Khūr",
    city_fa: "خور",
    lat: "33.7750",
    lng: "55.0831",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "6216",
    population_proper: "6216",
  },
  {
    city: "Ţāleqān",
    city_fa: "طالقان",
    lat: "36.1779",
    lng: "50.7655",
    country: "Iran",
    iso2: "IR",
    admin_name: "Alborz",
    capital: "minor",
    population: "3281",
    population_proper: "3281",
  },
  {
    city: "Chelgard",
    city_fa: "چلگرد",
    lat: "32.4681",
    lng: "50.1214",
    country: "Iran",
    iso2: "IR",
    admin_name: "Chahār Maḩāl va Bakhtīārī",
    capital: "minor",
    population: "2708",
    population_proper: "2708",
  },
  {
    city: "Bahār",
    city_fa: "بهار",
    lat: "34.9069",
    lng: "48.4414",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hamadān",
    capital: "minor",
    population: "27271",
    population_proper: "27271",
  },
  {
    city: "Sārī",
    city_fa: "ساری",
    lat: "36.5633",
    lng: "53.0601",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "admin",
    population: "",
    population_proper: "",
  },
  {
    city: "Īlām",
    city_fa: "ایلام",
    lat: "33.6374",
    lng: "46.4227",
    country: "Iran",
    iso2: "IR",
    admin_name: "Īlām",
    capital: "admin",
    population: "",
    population_proper: "",
  },
  {
    city: "Eshtehārd",
    city_fa: "اشتهارد",
    lat: "35.7256",
    lng: "50.3661",
    country: "Iran",
    iso2: "IR",
    admin_name: "Alborz",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Alvand",
    city_fa: "الوند",
    lat: "36.1892",
    lng: "50.0642",
    country: "Iran",
    iso2: "IR",
    admin_name: "Qazvīn",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Fereydūn Kenār",
    city_fa: "فریدون کنار",
    lat: "36.6861",
    lng: "52.5200",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Lāhījān",
    city_fa: "لاهیجان",
    lat: "37.2042",
    lng: "50.0092",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Maḩmūdābād",
    city_fa: "محمودآباد",
    lat: "36.6319",
    lng: "52.2629",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bābolsar",
    city_fa: "بابلسر",
    lat: "36.7000",
    lng: "52.6500",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bandar-e Torkaman",
    city_fa: "بندر ترکمن",
    lat: "36.9000",
    lng: "54.0667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Langarūd",
    city_fa: "لنگرود",
    lat: "37.1969",
    lng: "50.1536",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Jūybār",
    city_fa: "جویبار",
    lat: "36.6409",
    lng: "52.9121",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Āstāneh-ye Ashrafīyeh",
    city_fa: "آستانه اشرفیه",
    lat: "37.2597",
    lng: "49.9444",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Kangān",
    city_fa: "کنگان",
    lat: "27.8339",
    lng: "52.0628",
    country: "Iran",
    iso2: "IR",
    admin_name: "Būshehr",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bandar-e ‘Asalūyeh",
    city_fa: "بندر عسلویه",
    lat: "27.4761",
    lng: "52.6075",
    country: "Iran",
    iso2: "IR",
    admin_name: "Būshehr",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Āstārā",
    city_fa: "آستارا",
    lat: "38.4291",
    lng: "48.8720",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Şowme‘eh Sarā",
    city_fa: "شومره سرا",
    lat: "37.3117",
    lng: "49.3219",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bandar-e Gaz",
    city_fa: "بندر گز",
    lat: "36.7742",
    lng: "53.9481",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Hashtgerd",
    city_fa: "هشتگرد",
    lat: "35.9619",
    lng: "50.6800",
    country: "Iran",
    iso2: "IR",
    admin_name: "Alborz",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Fārsān",
    city_fa: "فارسان",
    lat: "32.2569",
    lng: "50.5642",
    country: "Iran",
    iso2: "IR",
    admin_name: "Chahār Maḩāl va Bakhtīārī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "‘Ajab Shīr",
    city_fa: "عجب شیر",
    lat: "37.4775",
    lng: "45.8942",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Khorramdarreh",
    city_fa: "خرم دره",
    lat: "36.2031",
    lng: "49.1869",
    country: "Iran",
    iso2: "IR",
    admin_name: "Zanjān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Pīshvā",
    city_fa: "پیشوا",
    lat: "35.3080",
    lng: "51.7267",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Rey",
    city_fa: "ری",
    lat: "35.5935",
    lng: "51.4400",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Pārsābād",
    city_fa: "پارس‌آباد",
    lat: "39.6482",
    lng: "47.9174",
    country: "Iran",
    iso2: "IR",
    admin_name: "Ardabīl",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Mīāndoāb",
    city_fa: "میاندوآب",
    lat: "36.9667",
    lng: "46.1096",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Narmāshīr",
    city_fa: "نرمشیر",
    lat: "28.9511",
    lng: "58.6953",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Māsāl",
    city_fa: "ماسال",
    lat: "37.3631",
    lng: "49.1329",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "‘Alīābād-e Katūl",
    city_fa: "علی‌آباد کتول",
    lat: "36.9101",
    lng: "54.8674",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Malekān",
    city_fa: "ملکان",
    lat: "37.1458",
    lng: "46.1028",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "‘Abbāsābād",
    city_fa: "عباس‌آباد",
    lat: "36.7277",
    lng: "51.1057",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ābādān",
    city_fa: "آبادان",
    lat: "30.3392",
    lng: "48.3043",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Nahāvand",
    city_fa: "نهاوند",
    lat: "34.1883",
    lng: "48.3769",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hamadān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Naqadeh",
    city_fa: "نقاده",
    lat: "36.9500",
    lng: "45.3833",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Behshahr",
    city_fa: "بهشهر",
    lat: "36.7000",
    lng: "53.5500",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Āzādshahr",
    city_fa: "آزادشهر",
    lat: "37.0864",
    lng: "55.1722",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Javānrūd",
    city_fa: "جوانرود",
    lat: "34.8067",
    lng: "46.4914",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Rāmīān",
    city_fa: "رامیان",
    lat: "37.0160",
    lng: "55.1412",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Zehak",
    city_fa: "زهک",
    lat: "30.8939",
    lng: "61.6803",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Rūdsar",
    city_fa: "رودسر",
    lat: "37.1375",
    lng: "50.2881",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Galūgāh",
    city_fa: "گلوگاه",
    lat: "36.7272",
    lng: "53.8089",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Rāmsar",
    city_fa: "رامسر",
    lat: "36.9169",
    lng: "50.6736",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Asadābād",
    city_fa: "اسدآباد",
    lat: "34.7822",
    lng: "48.1183",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hamadān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Shaft",
    city_fa: "شفته",
    lat: "37.1702",
    lng: "49.3998",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Nekā",
    city_fa: "نکا",
    lat: "36.6489",
    lng: "53.2958",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Kord Kūy",
    city_fa: "کردکوی",
    lat: "36.7931",
    lng: "54.1121",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Nowshahr",
    city_fa: "نورشهر",
    lat: "36.6450",
    lng: "51.5000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Harsīn",
    city_fa: "هرسین",
    lat: "34.2722",
    lng: "47.5861",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Gālīkesh",
    city_fa: "گالی‌کش",
    lat: "37.2719",
    lng: "55.4325",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Kavār",
    city_fa: "کاوار",
    lat: "29.2050",
    lng: "52.6897",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Chālūs",
    city_fa: "چالوس",
    lat: "36.6550",
    lng: "51.4204",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Āq Qalā",
    city_fa: "آق قلا",
    lat: "37.0139",
    lng: "54.4550",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Tonekābon",
    city_fa: "تنکابن",
    lat: "36.8167",
    lng: "50.8775",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Oskū",
    city_fa: "اسکوه",
    lat: "37.9158",
    lng: "46.1236",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Qeshm",
    city_fa: "قشم",
    lat: "26.9581",
    lng: "56.2717",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Eslāmābād-e Gharb",
    city_fa: "اسلام آباد غربی",
    lat: "34.1094",
    lng: "46.5275",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Pāveh",
    city_fa: "پاوه",
    lat: "35.0433",
    lng: "46.3564",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Dūst Moḩammad Khān",
    city_fa: "دوست محمد خان",
    lat: "31.1447",
    lng: "61.7925",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Mīnūdasht",
    city_fa: "مینودشت",
    lat: "37.2289",
    lng: "55.3747",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Tūyserkān",
    city_fa: "تویسرکان",
    lat: "34.5481",
    lng: "48.4467",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hamadān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Mollās̄ānī",
    city_fa: "ملکشاهی",
    lat: "31.5847",
    lng: "48.8859",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Namīn",
    city_fa: "نمین",
    lat: "38.4269",
    lng: "48.4839",
    country: "Iran",
    iso2: "IR",
    admin_name: "Ardabīl",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ābyek",
    city_fa: "آبیک",
    lat: "36.0542",
    lng: "50.5533",
    country: "Iran",
    iso2: "IR",
    admin_name: "Qazvīn",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Lordegān",
    city_fa: "لردگان",
    lat: "31.5097",
    lng: "50.8283",
    country: "Iran",
    iso2: "IR",
    admin_name: "Chahār Maḩāl va Bakhtīārī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Abhar",
    city_fa: "ابهر",
    lat: "36.2500",
    lng: "49.3667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Zanjān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Showţ",
    city_fa: "شوط",
    lat: "39.2192",
    lng: "44.7700",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ţorqabeh",
    city_fa: "طرقبه",
    lat: "36.3103",
    lng: "59.3736",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Dowlatābād",
    city_fa: "دولت آباد",
    lat: "32.7997",
    lng: "51.6953",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Shūsh",
    city_fa: "شوش",
    lat: "32.1942",
    lng: "48.2436",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Kūhdasht",
    city_fa: "کوهدشت",
    lat: "33.5300",
    lng: "47.6000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Lorestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Eyvān",
    city_fa: "ایوان",
    lat: "33.8272",
    lng: "46.3097",
    country: "Iran",
    iso2: "IR",
    admin_name: "Īlām",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Nūrābād",
    city_fa: "نورآباد",
    lat: "34.0734",
    lng: "47.9725",
    country: "Iran",
    iso2: "IR",
    admin_name: "Lorestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Āz̄arshahr",
    city_fa: "آذرشهر",
    lat: "37.7590",
    lng: "45.9783",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Şaḩneh",
    city_fa: "صحنه",
    lat: "34.4814",
    lng: "47.6908",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Kāmyārān",
    city_fa: "کامیاران",
    lat: "34.7956",
    lng: "46.9355",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kordestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Shahrak-e Bākharz",
    city_fa: "شهرک باخرز",
    lat: "34.9920",
    lng: "60.3171",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bāgh-e Malek",
    city_fa: "باغ ملک",
    lat: "31.5236",
    lng: "49.8894",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sīāhkal",
    city_fa: "سیاهکل",
    lat: "37.1528",
    lng: "49.8708",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Shabestar",
    city_fa: "شبستر",
    lat: "38.1803",
    lng: "45.7028",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Borūjen",
    city_fa: "بروجرد",
    lat: "31.9683",
    lng: "51.2894",
    country: "Iran",
    iso2: "IR",
    admin_name: "Chahār Maḩāl va Bakhtīārī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Kahnūj",
    city_fa: "کهنوج",
    lat: "27.9519",
    lng: "57.6996",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Jam",
    city_fa: "جم",
    lat: "27.8278",
    lng: "52.3267",
    country: "Iran",
    iso2: "IR",
    admin_name: "Būshehr",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Shādegān",
    city_fa: "شادگان",
    lat: "30.6497",
    lng: "48.6647",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Aleshtar",
    city_fa: "الیگودرز",
    lat: "33.8631",
    lng: "48.2617",
    country: "Iran",
    iso2: "IR",
    admin_name: "Lorestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Razan",
    city_fa: "رازان",
    lat: "35.3864",
    lng: "49.0336",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hamadān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Maşīrī",
    city_fa: "مشیری",
    lat: "30.2458",
    lng: "51.5223",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sareyn",
    city_fa: "سرعین",
    lat: "38.1514",
    lng: "48.0708",
    country: "Iran",
    iso2: "IR",
    admin_name: "Ardabīl",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Kalāleh",
    city_fa: "کلاله",
    lat: "37.3808",
    lng: "55.4917",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Qarah Ẕīā’ od Dīn",
    city_fa: "قره زیا الدین",
    lat: "38.8914",
    lng: "45.0253",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Shāzand",
    city_fa: "شازند",
    lat: "33.9275",
    lng: "49.4114",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sarvābād",
    city_fa: "سروآباد",
    lat: "35.3125",
    lng: "46.3667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kordestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Khomeyn",
    city_fa: "خمین",
    lat: "33.6422",
    lng: "50.0789",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Mīnāb",
    city_fa: "میناب",
    lat: "27.1310",
    lng: "57.0872",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Darreh Shahr",
    city_fa: "دره شهر",
    lat: "33.1397",
    lng: "47.3761",
    country: "Iran",
    iso2: "IR",
    admin_name: "Īlām",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Chenārān",
    city_fa: "چناران",
    lat: "36.6456",
    lng: "59.1211",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Nūr",
    city_fa: "نور",
    lat: "36.5717",
    lng: "52.0153",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sūsangerd",
    city_fa: "سوسنگرد",
    lat: "31.5608",
    lng: "48.1831",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Rūdān",
    city_fa: "رودان",
    lat: "27.4419",
    lng: "57.1920",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Gomīshān",
    city_fa: "گمیشان",
    lat: "37.0717",
    lng: "54.0767",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Omīdīyeh",
    city_fa: "امیدیه",
    lat: "30.7597",
    lng: "49.7050",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Tajrīsh",
    city_fa: "تجریش",
    lat: "35.8044",
    lng: "51.4256",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Shalamzār",
    city_fa: "شلمزار",
    lat: "32.0439",
    lng: "50.8139",
    country: "Iran",
    iso2: "IR",
    admin_name: "Chahār Maḩāl va Bakhtīārī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Dehdasht",
    city_fa: "دهدشت",
    lat: "30.7936",
    lng: "50.5650",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kohgīlūyeh va Bowyer Aḩmad",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Germī",
    city_fa: "گرمی",
    lat: "39.0214",
    lng: "48.0800",
    country: "Iran",
    iso2: "IR",
    admin_name: "Ardabīl",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Pā’īn-e Bāzār-e Rūdbār",
    city_fa: "پایین بازار رودبار",
    lat: "36.8211",
    lng: "49.4264",
    country: "Iran",
    iso2: "IR",
    admin_name: "Gīlān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ravānsar",
    city_fa: "روانسر",
    lat: "34.7153",
    lng: "46.6533",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Dārān",
    city_fa: "داران",
    lat: "32.9874",
    lng: "50.4108",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Meshgīn Shahr",
    city_fa: "مشگین شهر",
    lat: "38.3989",
    lng: "47.6819",
    country: "Iran",
    iso2: "IR",
    admin_name: "Ardabīl",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sonqor",
    city_fa: "سنقر",
    lat: "34.7836",
    lng: "47.6003",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bīleh Savār",
    city_fa: "بیله سوار",
    lat: "39.3796",
    lng: "48.3546",
    country: "Iran",
    iso2: "IR",
    admin_name: "Ardabīl",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Mohr",
    city_fa: "محرم",
    lat: "27.5550",
    lng: "52.8833",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Jolfā",
    city_fa: "جلفا",
    lat: "38.9353",
    lng: "45.6431",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Qorveh",
    city_fa: "قروه",
    lat: "35.1664",
    lng: "47.8044",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kordestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Estahbān",
    city_fa: "استهبان",
    lat: "29.1264",
    lng: "54.0419",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Dehgolān",
    city_fa: "دهگلان",
    lat: "35.2778",
    lng: "47.4183",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kordestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Do Gonbadān",
    city_fa: "دوگنبدان",
    lat: "30.3586",
    lng: "50.7981",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kohgīlūyeh va Bowyer Aḩmad",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Fīrūzābād",
    city_fa: "فیروزآباد",
    lat: "28.8438",
    lng: "52.5707",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bostānābād",
    city_fa: "بستان آباد",
    lat: "37.8463",
    lng: "46.8354",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Neqāb",
    city_fa: "نقاب",
    lat: "36.7081",
    lng: "57.4214",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Fārūj",
    city_fa: "فاروج",
    lat: "37.2312",
    lng: "58.2190",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Shomālī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Khalīlābād",
    city_fa: "خلیل آباد",
    lat: "35.2540",
    lng: "58.2857",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Mīāneh",
    city_fa: "میانه",
    lat: "37.4167",
    lng: "47.7000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sarābleh",
    city_fa: "سرابله",
    lat: "33.7667",
    lng: "46.5664",
    country: "Iran",
    iso2: "IR",
    admin_name: "Īlām",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sīsakht",
    city_fa: "سیسخت",
    lat: "30.8639",
    lng: "51.4558",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kohgīlūyeh va Bowyer Aḩmad",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sepīdān",
    city_fa: "سپیدان",
    lat: "30.2606",
    lng: "51.9842",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Arsanjān",
    city_fa: "ارسنجان",
    lat: "29.9122",
    lng: "53.3083",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sūrak",
    city_fa: "سورک",
    lat: "36.5950",
    lng: "53.2075",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sarāb-e Dūreh",
    city_fa: "سراب دوره",
    lat: "33.5628",
    lng: "48.0222",
    country: "Iran",
    iso2: "IR",
    admin_name: "Lorestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Joghtāy",
    city_fa: "جغتای",
    lat: "36.6350",
    lng: "57.0717",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Farīmān",
    city_fa: "فریمان",
    lat: "35.7069",
    lng: "59.8501",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bū’īn Zahrā",
    city_fa: "بویین زهراء",
    lat: "35.7669",
    lng: "50.0578",
    country: "Iran",
    iso2: "IR",
    admin_name: "Qazvīn",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Dārāb",
    city_fa: "داراب",
    lat: "28.7519",
    lng: "54.5444",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Farmahīn",
    city_fa: "فرمهین",
    lat: "34.5039",
    lng: "49.6844",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Rāmshīr",
    city_fa: "رامشیر",
    lat: "30.8947",
    lng: "49.4092",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Pol-e Sefīd",
    city_fa: "پل سفید",
    lat: "36.1178",
    lng: "53.0553",
    country: "Iran",
    iso2: "IR",
    admin_name: "Māzandarān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Herīs",
    city_fa: "هریس",
    lat: "38.2481",
    lng: "47.1167",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Maḩallāt",
    city_fa: "محلات",
    lat: "33.9054",
    lng: "50.4572",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Gāvbandī",
    city_fa: "گاوبندی",
    lat: "27.2083",
    lng: "53.0361",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bozghān",
    city_fa: "بزغان",
    lat: "36.2858",
    lng: "58.5861",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Līkak",
    city_fa: "لیکک",
    lat: "30.8950",
    lng: "50.0931",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kohgīlūyeh va Bowyer Aḩmad",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Gīlān-e Gharb",
    city_fa: "گیلان غرب",
    lat: "34.1422",
    lng: "45.9203",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Lālī",
    city_fa: "لالی",
    lat: "32.3298",
    lng: "49.0932",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Mākū",
    city_fa: "ماکو",
    lat: "39.2951",
    lng: "44.4982",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sarvestān",
    city_fa: "سروستان",
    lat: "29.2733",
    lng: "53.2203",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Charām",
    city_fa: "چرام",
    lat: "30.7460",
    lng: "50.7460",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kohgīlūyeh va Bowyer Aḩmad",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Dowlatābād",
    city_fa: "دولت آباد",
    lat: "35.2822",
    lng: "59.5197",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Hashtrūd",
    city_fa: "هشترود",
    lat: "37.4778",
    lng: "47.0508",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Deyr",
    city_fa: "دیر",
    lat: "27.8397",
    lng: "51.9378",
    country: "Iran",
    iso2: "IR",
    admin_name: "Būshehr",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Seyah Cheshmeh",
    city_fa: "چشمه سیاه",
    lat: "39.0728",
    lng: "44.3869",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Gharbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Delījān",
    city_fa: "دلیجان",
    lat: "33.9903",
    lng: "50.6836",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Tāzehābād",
    city_fa: "تازه‌آباد",
    lat: "34.7387",
    lng: "46.1496",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Khomārlū",
    city_fa: "خمارلو",
    lat: "39.1489",
    lng: "47.0347",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ardal",
    city_fa: "اردل",
    lat: "31.9961",
    lng: "50.6564",
    country: "Iran",
    iso2: "IR",
    admin_name: "Chahār Maḩāl va Bakhtīārī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ābbar",
    city_fa: "آبbar",
    lat: "36.9263",
    lng: "48.9583",
    country: "Iran",
    iso2: "IR",
    admin_name: "Zanjān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Qal‘eh-ye Khvājeh",
    city_fa: "قلعه خواجه",
    lat: "32.2064",
    lng: "49.4436",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Rābor",
    city_fa: "رابر",
    lat: "29.2911",
    lng: "56.9131",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Lāmerd",
    city_fa: "لامرد",
    lat: "27.3339",
    lng: "53.1789",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Zarrīnābād",
    city_fa: "زرین آباد",
    lat: "36.4250",
    lng: "48.2819",
    country: "Iran",
    iso2: "IR",
    admin_name: "Zanjān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Dīvāndarreh",
    city_fa: "دیواندره",
    lat: "35.9139",
    lng: "47.0239",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kordestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Şafāshahr",
    city_fa: "صفاشهر",
    lat: "30.6131",
    lng: "53.1954",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sīrīk",
    city_fa: "سیریک",
    lat: "26.5161",
    lng: "57.1019",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Kerend-e Gharb",
    city_fa: "کرند غربی",
    lat: "34.2842",
    lng: "46.2422",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermānshāh",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Nīr",
    city_fa: "نیرو",
    lat: "38.0346",
    lng: "47.9986",
    country: "Iran",
    iso2: "IR",
    admin_name: "Ardabīl",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Marāveh Tappeh",
    city_fa: "مروآوه تپه",
    lat: "37.9000",
    lng: "55.9500",
    country: "Iran",
    iso2: "IR",
    admin_name: "Golestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bandar-e Lengeh",
    city_fa: "بندر لنگه",
    lat: "26.5578",
    lng: "54.8806",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bāsht",
    city_fa: "باشت",
    lat: "30.3603",
    lng: "51.1617",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kohgīlūyeh va Bowyer Aḩmad",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Eslāmābād",
    city_fa: "اسلام‌آباد",
    lat: "28.0261",
    lng: "58.0000",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ābdānān",
    city_fa: "آبدانان",
    lat: "32.9926",
    lng: "47.4198",
    country: "Iran",
    iso2: "IR",
    admin_name: "Īlām",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Poldokhtar",
    city_fa: "پلدختر",
    lat: "33.1536",
    lng: "47.7136",
    country: "Iran",
    iso2: "IR",
    admin_name: "Lorestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bandar-e Deylam",
    city_fa: "بندر دیلم",
    lat: "30.0542",
    lng: "50.1589",
    country: "Iran",
    iso2: "IR",
    admin_name: "Būshehr",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Dargaz",
    city_fa: "درگز",
    lat: "37.3333",
    lng: "59.0833",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Gīvī",
    city_fa: "گیوی",
    lat: "37.6858",
    lng: "48.3420",
    country: "Iran",
    iso2: "IR",
    admin_name: "Ardabīl",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sa‘ādat Shahr",
    city_fa: "سعادت شهر",
    lat: "30.0786",
    lng: "53.1397",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Qīr",
    city_fa: "قیر",
    lat: "28.4825",
    lng: "53.0346",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Varazqān",
    city_fa: "ورزقان",
    lat: "38.6744",
    lng: "46.1131",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Fahraj",
    city_fa: "فهرج",
    lat: "28.9503",
    lng: "58.8850",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Āshkhāneh",
    city_fa: "آشخانه",
    lat: "37.5615",
    lng: "56.9212",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Shomālī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Solţānābād",
    city_fa: "سلطانیه",
    lat: "36.4035",
    lng: "58.0389",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ābādeh",
    city_fa: "آباده",
    lat: "31.1608",
    lng: "52.6506",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sarakhs",
    city_fa: "سرخس",
    lat: "36.5447",
    lng: "61.1575",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bastak",
    city_fa: "بستک",
    lat: "27.1992",
    lng: "54.3667",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ḩājjīābād",
    city_fa: "حاجی‌آباد",
    lat: "28.3574",
    lng: "54.4233",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Haftkel",
    city_fa: "هفتکل",
    lat: "31.4422",
    lng: "49.5317",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Khowrmūj",
    city_fa: "خورموج",
    lat: "28.6542",
    lng: "51.3800",
    country: "Iran",
    iso2: "IR",
    admin_name: "Būshehr",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Fīrūzkūh",
    city_fa: "فیروزکوه",
    lat: "35.7567",
    lng: "52.7706",
    country: "Iran",
    iso2: "IR",
    admin_name: "Tehrān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Shahr-e Qadīm-e Lār",
    city_fa: "شهر قدیم لار",
    lat: "27.6834",
    lng: "54.3417",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Nūrābād",
    city_fa: "نورآباد",
    lat: "30.1141",
    lng: "51.5217",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Rāsak",
    city_fa: "راستک",
    lat: "26.2368",
    lng: "61.3990",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Fāryāb",
    city_fa: "فاریاب",
    lat: "28.0987",
    lng: "57.2318",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Hoveyzeh",
    city_fa: "هوویزه",
    lat: "31.4619",
    lng: "48.0739",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "‘Anbarābād",
    city_fa: "انبارآباد",
    lat: "28.4758",
    lng: "57.8481",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Roshtkhvār",
    city_fa: "روشتخوار",
    lat: "34.9667",
    lng: "59.6167",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Anār",
    city_fa: "انار",
    lat: "30.8733",
    lng: "55.2706",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Manūjān",
    city_fa: "منوجان",
    lat: "27.4064",
    lng: "57.5014",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bandar-e Khamīr",
    city_fa: "بندر خمیر",
    lat: "26.9522",
    lng: "55.5850",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Arakvāz-e Malekshāhī",
    city_fa: "ارکواز ملکشاهی",
    lat: "33.3828",
    lng: "46.5983",
    country: "Iran",
    iso2: "IR",
    admin_name: "Īlām",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Arzū’īyeh",
    city_fa: "ارزوئیه",
    lat: "28.4414",
    lng: "56.3728",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Māmūnīyeh",
    city_fa: "مامونییه",
    lat: "35.3056",
    lng: "50.4992",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Māhneshān",
    city_fa: "ماه نشان",
    lat: "36.7442",
    lng: "47.6725",
    country: "Iran",
    iso2: "IR",
    admin_name: "Zanjān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Āshtīān",
    city_fa: "آشتیان",
    lat: "34.5219",
    lng: "50.0058",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Garmeh",
    city_fa: "گرمه",
    lat: "36.9833",
    lng: "56.2833",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Shomālī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Eqlīd",
    city_fa: "اقلید",
    lat: "30.8881",
    lng: "52.6850",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Nīkshahr",
    city_fa: "نیکشهر",
    lat: "26.2258",
    lng: "60.2142",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Neyrīz",
    city_fa: "نیریز",
    lat: "29.1986",
    lng: "54.3278",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Gonābād",
    city_fa: "گناباد",
    lat: "34.3528",
    lng: "58.6836",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Kalāt-e Nāderī",
    city_fa: "کلات نادر",
    lat: "36.9953",
    lng: "59.7647",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sūrīān",
    city_fa: "سوریان",
    lat: "30.4551",
    lng: "53.6510",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Zābolī",
    city_fa: "زابل",
    lat: "27.1310",
    lng: "61.6744",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Qarah Āghāj",
    city_fa: "قره آغاج",
    lat: "37.2187",
    lng: "47.2167",
    country: "Iran",
    iso2: "IR",
    admin_name: "Āz̄arbāyjān-e Sharqī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sūrān",
    city_fa: "سوران",
    lat: "27.2856",
    lng: "61.9964",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Konārak",
    city_fa: "کنارک",
    lat: "25.3603",
    lng: "60.3994",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Dehlorān",
    city_fa: "دهلران",
    lat: "32.6942",
    lng: "47.2678",
    country: "Iran",
    iso2: "IR",
    admin_name: "Īlām",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bardsīr",
    city_fa: "بردسیر",
    lat: "29.9275",
    lng: "56.5722",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Qā’en",
    city_fa: "قااین",
    lat: "33.7267",
    lng: "59.1844",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Jonūbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ḩājjīābād",
    city_fa: "حاجی‌آباد",
    lat: "33.6050",
    lng: "59.9934",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Jonūbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Moḩammadābād",
    city_fa: "محمدآباد",
    lat: "28.6689",
    lng: "59.0733",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Asadīyeh",
    city_fa: "اسدییه",
    lat: "32.9428",
    lng: "59.7200",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Jonūbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Khonj",
    city_fa: "خنج",
    lat: "27.8833",
    lng: "53.4333",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Īrānshahr",
    city_fa: "ایرانشهر",
    lat: "27.2024",
    lng: "60.6848",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Hendījān",
    city_fa: "هنديجان",
    lat: "30.2364",
    lng: "49.7119",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khūzestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Abarkūh",
    city_fa: "ابرکوه",
    lat: "31.1289",
    lng: "53.2822",
    country: "Iran",
    iso2: "IR",
    admin_name: "Yazd",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Tafresh",
    city_fa: "تفرش",
    lat: "34.6919",
    lng: "50.0128",
    country: "Iran",
    iso2: "IR",
    admin_name: "Markazī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Farāshband",
    city_fa: "فراشبند",
    lat: "28.8714",
    lng: "52.0917",
    country: "Iran",
    iso2: "IR",
    admin_name: "Fārs",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Qal‘eh Ganj",
    city_fa: "قلعه گنج",
    lat: "27.5236",
    lng: "57.8811",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Khāsh",
    city_fa: "خاش",
    lat: "28.2211",
    lng: "61.2158",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Jājarm",
    city_fa: "جاجرم",
    lat: "36.9501",
    lng: "56.3800",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Shomālī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ferdows",
    city_fa: "فردوس",
    lat: "34.0186",
    lng: "58.1722",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Jonūbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ḩājjīābād",
    city_fa: "حاجی‌آباد",
    lat: "28.3091",
    lng: "55.9017",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bajestān",
    city_fa: "باژستان",
    lat: "34.5164",
    lng: "58.1844",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Raẕavī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Mehrīz",
    city_fa: "مهریز",
    lat: "31.5853",
    lng: "54.4415",
    country: "Iran",
    iso2: "IR",
    admin_name: "Yazd",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Mehrān",
    city_fa: "مهران",
    lat: "33.1222",
    lng: "46.1647",
    country: "Iran",
    iso2: "IR",
    admin_name: "Īlām",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Shahr-e Bābak",
    city_fa: "شهر بابک",
    lat: "30.1164",
    lng: "55.1186",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Dalgān",
    city_fa: "دلگان",
    lat: "27.4753",
    lng: "59.4717",
    country: "Iran",
    iso2: "IR",
    admin_name: "Sīstān va Balūchestān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Kūhbanān",
    city_fa: "کوهبانان",
    lat: "31.4103",
    lng: "56.2825",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sardasht",
    city_fa: "سردشت",
    lat: "26.4558",
    lng: "57.9028",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sarbīsheh",
    city_fa: "سربیشه",
    lat: "32.5756",
    lng: "59.7983",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Jonūbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Mayāmey",
    city_fa: "میامی",
    lat: "36.4109",
    lng: "55.6502",
    country: "Iran",
    iso2: "IR",
    admin_name: "Semnān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Shahr-e Herāt",
    city_fa: "شهر هرات",
    lat: "30.0542",
    lng: "54.3731",
    country: "Iran",
    iso2: "IR",
    admin_name: "Yazd",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Boshrūyeh",
    city_fa: "بوشهر",
    lat: "33.8683",
    lng: "57.4289",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Jonūbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Bāfq",
    city_fa: "بافق",
    lat: "31.6053",
    lng: "55.4028",
    country: "Iran",
    iso2: "IR",
    admin_name: "Yazd",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Jāsk",
    city_fa: "جاسک",
    lat: "25.6439",
    lng: "57.7744",
    country: "Iran",
    iso2: "IR",
    admin_name: "Hormozgān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ardakān",
    city_fa: "اردکان",
    lat: "32.3094",
    lng: "54.0186",
    country: "Iran",
    iso2: "IR",
    admin_name: "Yazd",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Sarāyān",
    city_fa: "سارایان",
    lat: "33.8603",
    lng: "58.5217",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Jonūbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Rāvar",
    city_fa: "راور",
    lat: "31.2656",
    lng: "56.8056",
    country: "Iran",
    iso2: "IR",
    admin_name: "Kermān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Nehbandān",
    city_fa: "نهنبندان",
    lat: "31.5419",
    lng: "60.0364",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Jonūbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Ţabas",
    city_fa: "طبس",
    lat: "33.5959",
    lng: "56.9244",
    country: "Iran",
    iso2: "IR",
    admin_name: "Khorāsān-e Jonūbī",
    capital: "minor",
    population: "",
    population_proper: "",
  },
  {
    city: "Nā’īn",
    city_fa: "نائین",
    lat: "32.8601",
    lng: "53.0875",
    country: "Iran",
    iso2: "IR",
    admin_name: "Eşfahān",
    capital: "minor",
    population: "",
    population_proper: "",
  },
];
